CREATE OR REPLACE DATABASE   

CREATE SCHEMA IF NOT EXISTS BANKING_DWH.BRONZE;
CREATE SCHEMA IF NOT EXISTS BANKING_DWH.SILVER;
CREATE SCHEMA IF NOT EXISTS BANKING_DWH.GOLD;
SHOW DATABASES;
SHOW SCHEMAS;

CREATE OR REPLACE STAGE BANKING_DWH.BRONZE.BANKING_STAGE;

CREATE OR REPLACE FILE FORMAT BANKING_DWH.BRONZE.BANKING_CSV_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE;

SHOW FILE FORMATS IN SCHEMA BANKING_DWH.BRONZE;

LIST @BANKING_DWH.BRONZE.BANKING_STAGE;



DROP STAGE @BANKING_DWH.BRONZE.BANKING_JSON_STAGE;