USE DATABASE BANKING_DWH;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE_CUSTOMER (
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DATE_OF_BIRTH DATE,
    CITY VARCHAR,
    REGION VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATUS VARCHAR);

CREATE OR REPLACE TABLE BRONZE_ACCOUNT (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    ACCOUNT_STATUS VARCHAR,
    OPEN_DATE DATE
);

CREATE OR REPLACE TABLE BRONZE_TRANSACTION (
    TRANSACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE DATE,
    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_AMOUNT NUMBER(18,2),
    TRANSACTION_CHANNEL VARCHAR,
    TRANSACTION_STATUS VARCHAR
);

CREATE OR REPLACE TABLE BRONZE_LOAN (
    LOAN_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    LOAN_TYPE VARCHAR,
    LOAN_AMOUNT NUMBER(18,2),
    INTEREST_RATE NUMBER(5,2),
    START_DATE DATE,
    MATURITY_DATE DATE,
    LOAN_STATUS VARCHAR,
    OUTSTANDING_AMOUNT NUMBER(18,2)
);

CREATE OR REPLACE TABLE BRONZE_LOAN_PAYMENT (
    PAYMENT_ID VARCHAR,
    LOAN_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    PAYMENT_DATE DATE,
    PAYMENT_AMOUNT NUMBER(18,2),
    PRINCIPAL_AMOUNT NUMBER(18,2),
    INTEREST_AMOUNT NUMBER(18,2),
    PAYMENT_STATUS VARCHAR
);

SHOW TABLES;

---------- Initial Data loading from Stage to Bronze Tables

COPY INTO BRONZE_CUSTOMER
FROM @BANKING_STAGE/customers_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO BRONZE_ACCOUNT
FROM @BANKING_STAGE/accounts_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO BRONZE_TRANSACTION
FROM @BANKING_STAGE/transactions_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO BRONZE_LOAN
FROM @BANKING_STAGE/loans_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO BRONZE_LOAN_PAYMENT
FROM @BANKING_STAGE/loan_payments_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


---------- Validate Data count for each table


SELECT 'BRONZE_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM BRONZE_CUSTOMER
UNION ALL
SELECT 'BRONZE_ACCOUNT', COUNT(*) FROM BRONZE_ACCOUNT
UNION ALL
SELECT 'BRONZE_TRANSACTION', COUNT(*) FROM BRONZE_TRANSACTION
UNION ALL
SELECT 'BRONZE_LOAN', COUNT(*) FROM BRONZE_LOAN
UNION ALL
SELECT 'BRONZE_LOAN_PAYMENT', COUNT(*) FROM BRONZE_LOAN_PAYMENT;


---------- Checking for Duplicate records in each table.

SELECT CUSTOMER_ID, COUNT(*)
FROM BRONZE_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT ACCOUNT_ID, COUNT(*)
FROM BRONZE_ACCOUNT
GROUP BY ACCOUNT_ID
HAVING COUNT(*) > 1;

SELECT TRANSACTION_ID, COUNT(*)
FROM BRONZE_TRANSACTION
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1;

SELECT LOAN_ID, COUNT(*)
FROM BRONZE_LOAN
GROUP BY LOAN_ID
HAVING COUNT(*) > 1;

SELECT PAYMENT_ID, COUNT(*)
FROM BRONZE_LOAN_PAYMENT
GROUP BY PAYMENT_ID
HAVING COUNT(*) > 1;

