USE DATABASE BANKING_DWH;
USE SCHEMA GOLD;


CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DATE_OF_BIRTH DATE,
    CITY VARCHAR,
    REGION VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATUS VARCHAR,
    EFFECTIVE_FROM TIMESTAMP_NTZ,
    EFFECTIVE_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);

CREATE TABLE DIM_ACCOUNT (
    ACCOUNT_KEY NUMBER AUTOINCREMENT,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    ACCOUNT_STATUS VARCHAR,
    OPEN_DATE DATE
);


CREATE TABLE DIM_LOAN (
    LOAN_KEY NUMBER AUTOINCREMENT,
    LOAN_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    LOAN_TYPE VARCHAR,
    LOAN_AMOUNT NUMBER(18,2),
    INTEREST_RATE NUMBER(10,4),
    START_DATE DATE,
    MATURITY_DATE DATE,
    LOAN_STATUS VARCHAR,
    OUTSTANDING_AMOUNT NUMBER(18,2)
);



CREATE TABLE FACT_TRANSACTION (
    TRANSACTION_KEY NUMBER AUTOINCREMENT,
    TRANSACTION_ID VARCHAR,
    TRANSACTION_DATE DATE,
    ACCOUNT_KEY NUMBER,
    CUSTOMER_KEY NUMBER,
    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_AMOUNT NUMBER(18,2),
    TRANSACTION_CHANNEL VARCHAR,
    TRANSACTION_STATUS VARCHAR
);



CREATE TABLE FACT_LOAN_PAYMENT (
    PAYMENT_KEY NUMBER AUTOINCREMENT,
    PAYMENT_ID VARCHAR,
    PAYMENT_DATE DATE,
    LOAN_KEY NUMBER,
    CUSTOMER_KEY NUMBER,
    PAYMENT_AMOUNT NUMBER(18,2),
    PRINCIPAL_AMOUNT NUMBER(18,2),
    INTEREST_AMOUNT NUMBER(18,2),
    PAYMENT_STATUS VARCHAR
);

SHOW TABLES;

INSERT INTO BANKING_DWH.GOLD.DIM_CUSTOMER (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    REGION,
    CUSTOMER_SEGMENT,
    CUSTOMER_STATUS,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    REGION,
    CUSTOMER_SEGMENT,
    CUSTOMER_STATUS,
    TO_TIMESTAMP_NTZ('1900-01-01 00:00:00'),
    NULL,
    TRUE
FROM BANKING_DWH.SILVER.SILVER_CUSTOMER;



INSERT INTO DIM_ACCOUNT (
    ACCOUNT_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ACCOUNT_TYPE,
    ACCOUNT_STATUS,
    OPEN_DATE
)
SELECT
    ACCOUNT_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ACCOUNT_TYPE,
    ACCOUNT_STATUS,
    OPEN_DATE
FROM BANKING_DWH.SILVER.SILVER_ACCOUNT;


INSERT INTO DIM_LOAN (
    LOAN_ID,
    CUSTOMER_ID,
    LOAN_TYPE,
    LOAN_AMOUNT,
    INTEREST_RATE,
    START_DATE,
    MATURITY_DATE,
    LOAN_STATUS,
    OUTSTANDING_AMOUNT
)
SELECT
    LOAN_ID,
    CUSTOMER_ID,
    LOAN_TYPE,
    LOAN_AMOUNT,
    INTEREST_RATE,
    START_DATE,
    MATURITY_DATE,
    LOAN_STATUS,
    OUTSTANDING_AMOUNT
FROM BANKING_DWH.SILVER.SILVER_LOAN;


SELECT * FROM DIM_CUSTOMER;

SELECT COUNT(*) FROM DIM_CUSTOMER;
SELECT COUNT(*) FROM DIM_ACCOUNT;
SELECT COUNT(*) FROM DIM_LOAN;

INSERT INTO FACT_TRANSACTION (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    ACCOUNT_KEY,
    CUSTOMER_KEY,
    TRANSACTION_TYPE,
    TRANSACTION_AMOUNT,
    TRANSACTION_CHANNEL,
    TRANSACTION_STATUS
)
SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_DATE,
    a.ACCOUNT_KEY,
    c.CUSTOMER_KEY,
    t.TRANSACTION_TYPE,
    t.TRANSACTION_AMOUNT,
    t.TRANSACTION_CHANNEL,
    t.TRANSACTION_STATUS
FROM BANKING_DWH.SILVER.SILVER_TRANSACTION t
JOIN DIM_ACCOUNT a
    ON t.ACCOUNT_ID = a.ACCOUNT_ID
JOIN DIM_CUSTOMER c
    ON t.CUSTOMER_ID = c.CUSTOMER_ID
    AND t.TRANSACTION_DATE >= c.EFFECTIVE_FROM::DATE
    AND (
        t.TRANSACTION_DATE < c.EFFECTIVE_TO::DATE
        OR c.EFFECTIVE_TO IS NULL
    );

SELECT * FROM FACT_TRANSACTION;

INSERT INTO FACT_LOAN_PAYMENT (
    PAYMENT_ID,
    PAYMENT_DATE,
    LOAN_KEY,
    CUSTOMER_KEY,
    PAYMENT_AMOUNT,
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT,
    PAYMENT_STATUS
)
SELECT
    p.PAYMENT_ID,
    p.PAYMENT_DATE,
    l.LOAN_KEY,
    c.CUSTOMER_KEY,
    p.PAYMENT_AMOUNT,
    p.PRINCIPAL_AMOUNT,
    p.INTEREST_AMOUNT,
    p.PAYMENT_STATUS
FROM BANKING_DWH.SILVER.SILVER_LOAN_PAYMENT p
JOIN DIM_LOAN l
    ON p.LOAN_ID = l.LOAN_ID
JOIN DIM_CUSTOMER c
    ON p.CUSTOMER_ID = c.CUSTOMER_ID
    AND p.PAYMENT_DATE >= c.EFFECTIVE_FROM::DATE
    AND (
        p.PAYMENT_DATE < c.EFFECTIVE_TO::DATE
        OR c.EFFECTIVE_TO IS NULL
    );

SELECT 'DIM CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_CUSTOMER
UNION ALL
SELECT 'DIM ACCOUNT', COUNT(*) FROM DIM_ACCOUNT
UNION ALL
SELECT 'FACT TRANSACTION', COUNT(*) FROM FACT_TRANSACTION
UNION ALL
SELECT 'DIM LOAN', COUNT(*) FROM DIM_LOAN
UNION ALL
SELECT 'FACT LOAN_PAYMENT', COUNT(*) FROM FACT_LOAN_PAYMENT;

SELECT
    CUSTOMER_ID,
    COUNT(*) AS VERSION_COUNT
FROM GOLD.DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;