USE DATABASE BANKING_DWH;
USE SCHEMA BRONZE;

CREATE OR REPLACE PIPE PIPE_BRONZE_CUSTOMER
    AUTO_INGEST = FALSE
AS
COPY INTO BRONZE_CUSTOMER
FROM @BANKING_STAGE
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*customers_incremental_.*\.csv';

CREATE OR REPLACE PIPE PIPE_BRONZE_ACCOUNT
    AUTO_INGEST = FALSE
AS
COPY INTO BRONZE_ACCOUNT
FROM @BANKING_STAGE
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*accounts_incremental_.*\.csv';

CREATE OR REPLACE PIPE PIPE_BRONZE_TRANSACTION
    AUTO_INGEST = FALSE
AS
COPY INTO BRONZE_TRANSACTION
FROM @BANKING_STAGE
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*transactions_incremental_.*\.csv';

CREATE OR REPLACE PIPE PIPE_BRONZE_LOAN
    AUTO_INGEST = FALSE
AS
COPY INTO BRONZE_LOAN
FROM @BANKING_STAGE
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*loans_incremental_.*\.csv';

CREATE OR REPLACE PIPE PIPE_BRONZE_LOAN_PAYMENT
    AUTO_INGEST = FALSE
AS
COPY INTO BRONZE_LOAN_PAYMENT
FROM @BANKING_STAGE
FILE_FORMAT = (FORMAT_NAME = 'BANKING_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*loan_payments_incremental_.*\.csv';

SHOW PIPES;

ALTER PIPE PIPE_BRONZE_ACCOUNT REFRESH;

ALTER PIPE PIPE_BRONZE_CUSTOMER REFRESH;

ALTER PIPE PIPE_BRONZE_LOAN REFRESH;

ALTER PIPE PIPE_BRONZE_LOAN_PAYMENT REFRESH;

ALTER PIPE PIPE_BRONZE_TRANSACTION REFRESH;


SELECT SYSTEM$PIPE_STATUS('PIPE_BRONZE_ACCOUNT');

SELECT SYSTEM$PIPE_STATUS('PIPE_BRONZE_CUSTOMER');

SELECT SYSTEM$PIPE_STATUS('PIPE_BRONZE_LOAN');

SELECT SYSTEM$PIPE_STATUS('PIPE_BRONZE_LOAN_PAYMENT');

SELECT SYSTEM$PIPE_STATUS('PIPE_BRONZE_TRANSACTION');