USE DATABASE BANKING_DWH;
USE SCHEMA BRONZE;


DROP STREAM IF EXISTS STR_BRONZE_CUSTOMER;
DROP STREAM IF EXISTS STR_BRONZE_ACCOUNT;
DROP STREAM IF EXISTS STR_BRONZE_LOAN;
DROP STREAM IF EXISTS STR_BRONZE_TRANSACTION;
DROP STREAM IF EXISTS STR_BRONZE_LOAN_PAYMENT;
show streams;

CREATE STREAM STR_BRONZE_CUSTOMER
ON TABLE BRONZE_CUSTOMER;

CREATE STREAM STR_BRONZE_ACCOUNT
ON TABLE BRONZE_ACCOUNT;

CREATE STREAM STR_BRONZE_TRANSACTION
ON TABLE BRONZE_TRANSACTION
APPEND_ONLY = TRUE;

CREATE STREAM STR_BRONZE_LOAN
ON TABLE BRONZE_LOAN;

CREATE STREAM STR_BRONZE_LOAN_PAYMENT
ON TABLE BRONZE_LOAN_PAYMENT
APPEND_ONLY = TRUE;

SHOW STREAMS;

SELECT 'CUSTOMER' AS STREAM_NAME, COUNT(*) AS ROW_COUNT FROM BRONZE.STR_BRONZE_CUSTOMER
UNION ALL
SELECT 'ACCOUNT', COUNT(*) FROM BRONZE.STR_BRONZE_ACCOUNT
UNION ALL
SELECT 'LOAN', COUNT(*) FROM BRONZE.STR_BRONZE_LOAN
UNION ALL
SELECT 'LOAN_PAYMENT', COUNT(*) FROM BRONZE.STR_BRONZE_LOAN_PAYMENT
UNION ALL
SELECT 'TRANSACTION', COUNT(*) FROM BRONZE.STR_BRONZE_TRANSACTION;

------- STREAMS ON SILVER TABLES ------

USE SCHEMA SILVER;


CREATE OR REPLACE STREAM SILVER.STR_SILVER_CUSTOMER
ON TABLE SILVER.SILVER_CUSTOMER;

CREATE OR REPLACE STREAM SILVER.STR_SILVER_ACCOUNT
ON TABLE SILVER.SILVER_ACCOUNT;

CREATE OR REPLACE STREAM SILVER.STR_SILVER_LOAN
ON TABLE SILVER.SILVER_LOAN;

CREATE OR REPLACE STREAM SILVER.STR_SILVER_LOAN_PAYMENT
ON TABLE SILVER.SILVER_LOAN_PAYMENT;

CREATE OR REPLACE STREAM SILVER.STR_SILVER_TRANSACTION
ON TABLE SILVER.SILVER_TRANSACTION;


SHOW STREAMS;

USE DATABASE BANKING_DWH;
USE SCHEMA SILVER;

SELECT 'CUSTOMER' AS STREAM_NAME, COUNT(*) AS ROW_COUNT FROM STR_SILVER_CUSTOMER
UNION ALL
SELECT 'ACCOUNT', COUNT(*) FROM STR_SILVER_ACCOUNT
UNION ALL
SELECT 'LOAN', COUNT(*) FROM STR_SILVER_LOAN
UNION ALL
SELECT 'LOAN_PAYMENT', COUNT(*) FROM STR_SILVER_LOAN_PAYMENT
UNION ALL
SELECT 'TRANSACTION', COUNT(*) FROM STR_SILVER_TRANSACTION;