USE DATABASE BANKING_DWH;
USE SCHEMA SILVER;

---------- CREATE TASK TO LOAD DATA INTO SILVER TABLES FROM BRONZE STREAMS

---------- 1. CUSTOMER TASK


CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER_CUSTOMER
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'BANKING_DWH.BRONZE.STR_BRONZE_CUSTOMER'
    )
AS
MERGE INTO SILVER_CUSTOMER t
USING (
    SELECT
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        GENDER,
        DATE_OF_BIRTH,
        CITY,
        REGION,
        CUSTOMER_SEGMENT,
        CUSTOMER_STATUS
    FROM BANKING_DWH.BRONZE.STR_BRONZE_CUSTOMER
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CUSTOMER_ID
        ORDER BY METADATA$ROW_ID DESC
    ) = 1
) s
ON t.CUSTOMER_ID = s.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    t.FIRST_NAME = s.FIRST_NAME,
    t.LAST_NAME = s.LAST_NAME,
    t.GENDER = s.GENDER,
    t.DATE_OF_BIRTH = s.DATE_OF_BIRTH,
    t.CITY = s.CITY,
    t.REGION = s.REGION,
    t.CUSTOMER_SEGMENT = s.CUSTOMER_SEGMENT,
    t.CUSTOMER_STATUS = s.CUSTOMER_STATUS

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    REGION,
    CUSTOMER_SEGMENT,
    CUSTOMER_STATUS
)
VALUES (
    s.CUSTOMER_ID,
    s.FIRST_NAME,
    s.LAST_NAME,
    s.GENDER,
    s.DATE_OF_BIRTH,
    s.CITY,
    s.REGION,
    s.CUSTOMER_SEGMENT,
    s.CUSTOMER_STATUS
);



---------- 2. ACCOUNT TASK


CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER_ACCOUNT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'BANKING_DWH.BRONZE.STR_BRONZE_ACCOUNT'
    )
AS
MERGE INTO SILVER_ACCOUNT t
USING (
    SELECT
        ACCOUNT_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        ACCOUNT_TYPE,
        ACCOUNT_STATUS,
        OPEN_DATE
    FROM BANKING_DWH.BRONZE.STR_BRONZE_ACCOUNT
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACCOUNT_ID
        ORDER BY METADATA$ROW_ID DESC
    ) = 1
) s
ON t.ACCOUNT_ID = s.ACCOUNT_ID

WHEN MATCHED THEN UPDATE SET
    t.CUSTOMER_ID = s.CUSTOMER_ID,
    t.PRODUCT_ID = s.PRODUCT_ID,
    t.ACCOUNT_TYPE = s.ACCOUNT_TYPE,
    t.ACCOUNT_STATUS = s.ACCOUNT_STATUS,
    t.OPEN_DATE = s.OPEN_DATE

WHEN NOT MATCHED THEN INSERT (
    ACCOUNT_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ACCOUNT_TYPE,
    ACCOUNT_STATUS,
    OPEN_DATE
)
VALUES (
    s.ACCOUNT_ID,
    s.CUSTOMER_ID,
    s.PRODUCT_ID,
    s.ACCOUNT_TYPE,
    s.ACCOUNT_STATUS,
    s.OPEN_DATE
);


---------- 3. LOAN TASK

CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER_LOAN
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'BANKING_DWH.BRONZE.STR_BRONZE_LOAN'
    )
AS
MERGE INTO SILVER_LOAN t
USING (
    SELECT
        LOAN_ID,
        CUSTOMER_ID,
        LOAN_TYPE,
        LOAN_AMOUNT,
        INTEREST_RATE,
        START_DATE,
        MATURITY_DATE,
        LOAN_STATUS,
        OUTSTANDING_AMOUNT
    FROM BANKING_DWH.BRONZE.STR_BRONZE_LOAN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY LOAN_ID
        ORDER BY METADATA$ROW_ID DESC
    ) = 1
) s
ON t.LOAN_ID = s.LOAN_ID

WHEN MATCHED THEN UPDATE SET
    t.CUSTOMER_ID = s.CUSTOMER_ID,
    t.LOAN_TYPE = s.LOAN_TYPE,
    t.LOAN_AMOUNT = s.LOAN_AMOUNT,
    t.INTEREST_RATE = s.INTEREST_RATE,
    t.START_DATE = s.START_DATE,
    t.MATURITY_DATE = s.MATURITY_DATE,
    t.LOAN_STATUS = s.LOAN_STATUS,
    t.OUTSTANDING_AMOUNT = s.OUTSTANDING_AMOUNT

WHEN NOT MATCHED THEN INSERT (
    LOAN_ID,
    CUSTOMER_ID,
    LOAN_TYPE,
    LOAN_AMOUNT,
    INTEREST_RATE,
    START_DATE,
    MATURITY_DATE,
    LOAN_STATUS,
    OUTSTANDING_AMOUNT
)
VALUES (
    s.LOAN_ID,
    s.CUSTOMER_ID,
    s.LOAN_TYPE,
    s.LOAN_AMOUNT,
    s.INTEREST_RATE,
    s.START_DATE,
    s.MATURITY_DATE,
    s.LOAN_STATUS,
    s.OUTSTANDING_AMOUNT
);


---------- 4. TRANSACTION TASK

CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER_TRANSACTION
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'BANKING_DWH.BRONZE.STR_BRONZE_TRANSACTION'
    )
AS
INSERT INTO SILVER_TRANSACTION (
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    TRANSACTION_DATE,
    TRANSACTION_TYPE,
    TRANSACTION_AMOUNT,
    TRANSACTION_CHANNEL,
    TRANSACTION_STATUS
)
SELECT
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    TRANSACTION_DATE,
    TRANSACTION_TYPE,
    TRANSACTION_AMOUNT,
    TRANSACTION_CHANNEL,
    TRANSACTION_STATUS
FROM BANKING_DWH.BRONZE.STR_BRONZE_TRANSACTION;


---------- 5. LOAN PAYMENT TASK


CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER_LOAN_PAYMENT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'BANKING_DWH.BRONZE.STR_BRONZE_LOAN_PAYMENT'
    )
AS
INSERT INTO SILVER_LOAN_PAYMENT (
    PAYMENT_ID,
    LOAN_ID,
    CUSTOMER_ID,
    PAYMENT_DATE,
    PAYMENT_AMOUNT,
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT,
    PAYMENT_STATUS
)
SELECT
    PAYMENT_ID,
    LOAN_ID,
    CUSTOMER_ID,
    PAYMENT_DATE,
    PAYMENT_AMOUNT,
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT,
    PAYMENT_STATUS
FROM BANKING_DWH.BRONZE.STR_BRONZE_LOAN_PAYMENT;

SHOW TASKS IN SCHEMA BANKING_DWH.SILVER;

---------- Resume All the TASK to COPY data from Bronze Stream to Silver Tables


ALTER TASK TASK_BRONZE_TO_SILVER_CUSTOMER RESUME;
ALTER TASK TASK_BRONZE_TO_SILVER_ACCOUNT RESUME;
ALTER TASK TASK_BRONZE_TO_SILVER_LOAN RESUME;
ALTER TASK TASK_BRONZE_TO_SILVER_TRANSACTION RESUME;
ALTER TASK TASK_BRONZE_TO_SILVER_LOAN_PAYMENT RESUME;

---------- Suspend All the TASK

ALTER TASK TASK_BRONZE_TO_SILVER_CUSTOMER SUSPEND;
ALTER TASK TASK_BRONZE_TO_SILVER_ACCOUNT SUSPEND;
ALTER TASK TASK_BRONZE_TO_SILVER_LOAN SUSPEND;
ALTER TASK TASK_BRONZE_TO_SILVER_TRANSACTION SUSPEND;
ALTER TASK TASK_BRONZE_TO_SILVER_LOAN_PAYMENT SUSPEND;