USE DATABASE BANKING_DWH;
USE SCHEMA GOLD;

---------- CREATE TASK TO CAPTURE DATA FROM SILVER STREAMS TO GOLD TABLES, TASK SCHEDULED EVERY 1 MINUTE

---------- CUSTOMER DIMENSION TABLE IS OF SCD TYPE 2 ,ACCOUNT AND LOAD DIMENSION TABLES ARE OF SCD TYPE 1

 
---------- 1. CUSTOMER - SCD TYPE 2 TASK 

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_CUSTOMER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BANKING_DWH.SILVER.STR_SILVER_CUSTOMER'
)
AS

MERGE INTO GOLD.DIM_CUSTOMER d

USING
(
    -- EXPIRE CURRENT RECORD WHEN TRACKED ATTRIBUTES CHANGE
    SELECT
        s.CUSTOMER_ID,
        s.FIRST_NAME,
        s.LAST_NAME,
        s.GENDER,
        s.DATE_OF_BIRTH,
        s.CITY,
        s.REGION,
        s.CUSTOMER_SEGMENT,
        s.CUSTOMER_STATUS,
        'EXPIRE' AS CHANGE_TYPE

    FROM SILVER.STR_SILVER_CUSTOMER s

    JOIN GOLD.DIM_CUSTOMER d
        ON d.CUSTOMER_ID = s.CUSTOMER_ID
       AND d.IS_CURRENT = TRUE

    WHERE s.METADATA$ACTION = 'INSERT'
      AND (
            d.CITY IS DISTINCT FROM s.CITY
         OR d.REGION IS DISTINCT FROM s.REGION
         OR d.CUSTOMER_SEGMENT IS DISTINCT FROM s.CUSTOMER_SEGMENT
         OR d.CUSTOMER_STATUS IS DISTINCT FROM s.CUSTOMER_STATUS
      )

    UNION ALL

    -- -----------------------------------------------------
    -- INSERT NEW CUSTOMER OR NEW SCD TYPE 2 VERSION
    -- -----------------------------------------------------
    SELECT
        s.CUSTOMER_ID,
        s.FIRST_NAME,
        s.LAST_NAME,
        s.GENDER,
        s.DATE_OF_BIRTH,
        s.CITY,
        s.REGION,
        s.CUSTOMER_SEGMENT,
        s.CUSTOMER_STATUS,
        'INSERT' AS CHANGE_TYPE

    FROM SILVER.STR_SILVER_CUSTOMER s

    LEFT JOIN GOLD.DIM_CUSTOMER d
        ON d.CUSTOMER_ID = s.CUSTOMER_ID
       AND d.IS_CURRENT = TRUE

    WHERE s.METADATA$ACTION = 'INSERT'
      AND (
            d.CUSTOMER_ID IS NULL
         OR d.CITY IS DISTINCT FROM s.CITY
         OR d.REGION IS DISTINCT FROM s.REGION
         OR d.CUSTOMER_SEGMENT IS DISTINCT FROM s.CUSTOMER_SEGMENT
         OR d.CUSTOMER_STATUS IS DISTINCT FROM s.CUSTOMER_STATUS
      )
) s

ON d.CUSTOMER_ID = s.CUSTOMER_ID
AND d.IS_CURRENT = TRUE
AND s.CHANGE_TYPE = 'EXPIRE'

WHEN MATCHED THEN
    UPDATE SET
        d.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        d.IS_CURRENT = FALSE

WHEN NOT MATCHED
     AND s.CHANGE_TYPE = 'INSERT'
THEN
    INSERT
    (
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        GENDER,
        DATE_OF_BIRTH,
        CITY,
        REGION,
        CUSTOMER_SEGMENT,
        CUSTOMER_STATUS,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT
    )
    VALUES
    (
        s.CUSTOMER_ID,
        s.FIRST_NAME,
        s.LAST_NAME,
        s.GENDER,
        s.DATE_OF_BIRTH,
        s.CITY,
        s.REGION,
        s.CUSTOMER_SEGMENT,
        s.CUSTOMER_STATUS,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    );


-- =========================================================
-- 2. ACCOUNT - SCD TYPE 1
-- INDEPENDENT TASK
-- RUNS EVERY 1 MINUTE
-- =========================================================

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_ACCOUNT
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BANKING_DWH.SILVER.STR_SILVER_ACCOUNT'
)
AS

MERGE INTO GOLD.DIM_ACCOUNT d

USING
(
    SELECT
        ACCOUNT_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        ACCOUNT_TYPE,
        ACCOUNT_STATUS,
        OPEN_DATE
    FROM SILVER.STR_SILVER_ACCOUNT
) s

ON d.ACCOUNT_ID = s.ACCOUNT_ID

WHEN MATCHED THEN
    UPDATE SET
        d.CUSTOMER_ID = s.CUSTOMER_ID,
        d.PRODUCT_ID = s.PRODUCT_ID,
        d.ACCOUNT_TYPE = s.ACCOUNT_TYPE,
        d.ACCOUNT_STATUS = s.ACCOUNT_STATUS,
        d.OPEN_DATE = s.OPEN_DATE

WHEN NOT MATCHED THEN
    INSERT
    (
        ACCOUNT_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        ACCOUNT_TYPE,
        ACCOUNT_STATUS,
        OPEN_DATE
    )
    VALUES
    (
        s.ACCOUNT_ID,
        s.CUSTOMER_ID,
        s.PRODUCT_ID,
        s.ACCOUNT_TYPE,
        s.ACCOUNT_STATUS,
        s.OPEN_DATE
    );


-- =========================================================
-- 3. LOAN - SCD TYPE 1
-- INDEPENDENT TASK
-- RUNS EVERY 1 MINUTE
-- =========================================================

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_LOAN
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BANKING_DWH.SILVER.STR_SILVER_LOAN'
)
AS

MERGE INTO GOLD.DIM_LOAN d

USING
(
    SELECT
        LOAN_ID,
        CUSTOMER_ID,
        LOAN_TYPE,
        LOAN_AMOUNT,
        INTEREST_RATE,
        START_DATE,
        MATURITY_DATE,
        LOAN_STATUS,
        OUTSTANDING_AMOUNT
    FROM SILVER.STR_SILVER_LOAN
) s

ON d.LOAN_ID = s.LOAN_ID

WHEN MATCHED THEN
    UPDATE SET
        d.CUSTOMER_ID = s.CUSTOMER_ID,
        d.LOAN_TYPE = s.LOAN_TYPE,
        d.LOAN_AMOUNT = s.LOAN_AMOUNT,
        d.INTEREST_RATE = s.INTEREST_RATE,
        d.START_DATE = s.START_DATE,
        d.MATURITY_DATE = s.MATURITY_DATE,
        d.LOAN_STATUS = s.LOAN_STATUS,
        d.OUTSTANDING_AMOUNT = s.OUTSTANDING_AMOUNT

WHEN NOT MATCHED THEN
    INSERT
    (
        LOAN_ID,
        CUSTOMER_ID,
        LOAN_TYPE,
        LOAN_AMOUNT,
        INTEREST_RATE,
        START_DATE,
        MATURITY_DATE,
        LOAN_STATUS,
        OUTSTANDING_AMOUNT
    )
    VALUES
    (
        s.LOAN_ID,
        s.CUSTOMER_ID,
        s.LOAN_TYPE,
        s.LOAN_AMOUNT,
        s.INTEREST_RATE,
        s.START_DATE,
        s.MATURITY_DATE,
        s.LOAN_STATUS,
        s.OUTSTANDING_AMOUNT
    );


-- =========================================================
-- 4. TRANSACTION FACT
-- INDEPENDENT TASK
-- RUNS EVERY 1 MINUTE
-- =========================================================

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_TRANSACTION
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BANKING_DWH.SILVER.STR_SILVER_TRANSACTION'
)
AS

INSERT INTO GOLD.FACT_TRANSACTION
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    ACCOUNT_KEY,
    CUSTOMER_KEY,
    TRANSACTION_TYPE,
    TRANSACTION_AMOUNT,
    TRANSACTION_CHANNEL,
    TRANSACTION_STATUS
)

SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_DATE,
    a.ACCOUNT_KEY,
    c.CUSTOMER_KEY,
    t.TRANSACTION_TYPE,
    t.TRANSACTION_AMOUNT,
    t.TRANSACTION_CHANNEL,
    t.TRANSACTION_STATUS

FROM SILVER.STR_SILVER_TRANSACTION t

JOIN GOLD.DIM_ACCOUNT a
    ON t.ACCOUNT_ID = a.ACCOUNT_ID

JOIN GOLD.DIM_CUSTOMER c
    ON t.CUSTOMER_ID = c.CUSTOMER_ID
   AND t.TRANSACTION_DATE >= c.EFFECTIVE_FROM::DATE
   AND (
        t.TRANSACTION_DATE < c.EFFECTIVE_TO::DATE
        OR c.EFFECTIVE_TO IS NULL
   );


-- =========================================================
-- 5. LOAN PAYMENT FACT
-- INDEPENDENT TASK
-- RUNS EVERY 1 MINUTE
-- =========================================================

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_LOAN_PAYMENT
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BANKING_DWH.SILVER.STR_SILVER_LOAN_PAYMENT'
)
AS

INSERT INTO GOLD.FACT_LOAN_PAYMENT
(
    PAYMENT_ID,
    PAYMENT_DATE,
    LOAN_KEY,
    CUSTOMER_KEY,
    PAYMENT_AMOUNT,
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT,
    PAYMENT_STATUS
)

SELECT
    p.PAYMENT_ID,
    p.PAYMENT_DATE,
    l.LOAN_KEY,
    c.CUSTOMER_KEY,
    p.PAYMENT_AMOUNT,
    p.PRINCIPAL_AMOUNT,
    p.INTEREST_AMOUNT,
    p.PAYMENT_STATUS

FROM SILVER.STR_SILVER_LOAN_PAYMENT p

JOIN GOLD.DIM_LOAN l
    ON p.LOAN_ID = l.LOAN_ID

JOIN GOLD.DIM_CUSTOMER c
    ON p.CUSTOMER_ID = c.CUSTOMER_ID
   AND p.PAYMENT_DATE >= c.EFFECTIVE_FROM::DATE
   AND (
        p.PAYMENT_DATE < c.EFFECTIVE_TO::DATE
        OR c.EFFECTIVE_TO IS NULL
   );


-- =========================================================
-- VERIFY ALL 5 TASKS
-- =========================================================

SHOW TASKS;

ALTER TASK TASK_SILVER_TO_GOLD_CUSTOMER RESUME;
ALTER TASK TASK_SILVER_TO_GOLD_ACCOUNT RESUME;
ALTER TASK TASK_SILVER_TO_GOLD_LOAN RESUME;
ALTER TASK TASK_SILVER_TO_GOLD_TRANSACTION RESUME;
ALTER TASK TASK_SILVER_TO_GOLD_LOAN_PAYMENT RESUME;

ALTER TASK TASK_SILVER_TO_GOLD_CUSTOMER SUSPEND;
ALTER TASK TASK_SILVER_TO_GOLD_ACCOUNT SUSPEND;
ALTER TASK TASK_SILVER_TO_GOLD_LOAN SUSPEND;
ALTER TASK TASK_SILVER_TO_GOLD_TRANSACTION SUSPEND;
ALTER TASK TASK_SILVER_TO_GOLD_LOAN_PAYMENT SUSPEND;

SHOW TASKS;